package demo;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import org.junit.Before;
import org.junit.After;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.containsString;

public class HelloGradleTest {
    private final ByteArrayOutputStream output = new ByteArrayOutputStream();
	

	@Before
	public void setup() {
		System.setOut(new PrintStream(output));
	}

	@After
	public void cleanUpStreams() {
		System.setOut(null);
	}


	@Test
	public void shouldPrintHelloToConsole() {
		HelloGradle helloGradle = new HelloGradle();
		helloGradle.printGradle();
		assertEquals("Hello Gradle!\n", output.toString());
	}



}
