package demo;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HelloGradle {

    public void printGradle()
    {
        System.out.println("Hello Gradle!");
    }


}
